export const phoneCodeOptions = [
  { label: 'United States / Canada (+1)', value: '+1' },
  { label: 'United Kingdom (+44)', value: '+44' },
  { label: 'Germany (+49)', value: '+49' },
  { label: 'France (+33)', value: '+33' },
  { label: 'Italy (+39)', value: '+39' },
  { label: 'Spain (+34)', value: '+34' },
  { label: 'Netherlands (+31)', value: '+31' },
  { label: 'Sweden (+46)', value: '+46' },
  { label: 'Norway (+47)', value: '+47' },
  { label: 'Australia (+61)', value: '+61' },
  { label: 'New Zealand (+64)', value: '+64' },
  { label: 'Japan (+81)', value: '+81' },
  { label: 'South Korea (+82)', value: '+82' },
  { label: 'Singapore (+65)', value: '+65' },
  { label: 'China (+86)', value: '+86' },
  { label: 'India (+91)', value: '+91' },
  { label: 'United Arab Emirates (+971)', value: '+971' },
  { label: 'Saudi Arabia (+966)', value: '+966' },
  { label: 'Brazil (+55)', value: '+55' },
  { label: 'Mexico (+52)', value: '+52' },
] as const
